name: Deploy Functions

on:
  push:
    branches:
      - master
    paths:
      - 'apps/functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: { 'node-version': '22' }

      - name: Build functions TS
        run: |
          cd apps/functions
          npm ci
          npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Firebase Functions
        run: firebase deploy --only functions --project ${{ secrets.GCP_PROJECT }} --force

      - name: Send Discord notification
        run: |
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          curl -s -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"💽 [VideoMaker][Functions] deployed! Commit: $LAST_COMMIT_MESSAGE\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
