name: Deploy Functions

on:
  push:
    branches:
      - master
    paths:
      - 'apps/functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: { 'node-version': '22' }

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.TOKEN_GITHUB_PERSONAL_ACC }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VISUALIZATIONMAKER_B8FF1 }}'
          channelId: live

      - name: Deploy Functions
        run: |
          cd apps/functions
          npm ci
          npm run build
          firebase deploy --only functions
